const GET_PRODUCT_ALL = 'GET_PRODUCT_ALL';
const GET_PROCESS_ALL = 'GET_PROCESS_ALL';
const FILTER_BY_ORDER = 'FILTER_BY_ORDER';
const FILTER_BY_PROCESS = 'FILTER_BY_PROCESS';
const CREATE_PRODUCT = 'CREATE_PRODUCT';
const CLEAR_ALL = 'CLEAR_ALL';

module.exports = {
    GET_PRODUCT_ALL,
    GET_PROCESS_ALL,
    FILTER_BY_ORDER,
    FILTER_BY_PROCESS,
    CREATE_PRODUCT,
    CLEAR_ALL,
}